### ISSUE TITLE
not working on { } layers

### ISSUE THREAD

**Issue by synthview** [RafalBuchner/StemThickness#15]
Hello,
I really love your plugin, however it doesn’t seem to work on bracket layers.
Also, to make it work on normal layers I have to activate Crosshair pluging too to make yours display its lines :/ I guess something is going wrong with UI refreshing (this issue is there since a long time already).

**Comment by mekkablue** [comment]
I guess this has been fixed a while ago? I cannot reproduce this.

**Comment by synthview** [comment]
Hi, in fact it still randomly happens, but I can't find any pattern
