### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by MajusCorp** [RafalBuchner/StemThickness#2]
Using Glyphs Plugin Manager, the plugin does not install. The progress bar starts, than bounces back to the beginning, leaving the word "Install". This was true in Build [911] and now in Build [913].

**Comment by dyyybek** [comment]
This happens to me too 2.3.1 [899].

**Comment by RafalBuchner** [comment]
I' m working on this issue. In following weeks it should be ok

W dniu czwartek, 22 września 2016 Marcin Dybaś <notifications@github.com>
napisał(a):
